version: '3.7'
services:
  
  jira:
    container_name: jira-container
    image: atlassian/jira-software:latest 
    hostname: multi-compose-host
    volumes:
        - './jira:/var/atlassian/jira:Z'
    ports:      
        - "2200:8080"
    networks:
      - multi-compose-network

networks:
  multi-compose-network:
    name: multi-compose-network